import React from 'react';
import styled from 'styled-components';

import { Description, Subtitle, Title, PageRoot } from './components';

const LinksContainer = styled.div`
	max-width: 300px;
	width: 100%;
	display: flex;
	flex-wrap: wrap;
	justify-content: space-between;
`;

const Link = styled.a`
	color: ${props => props.theme.colors.primary.main};
	text-decoration: none;
	:visited {
		color: ${props => props.theme.colors.primary.main};
	}
`;

const Certificates = () => {
	return (
		<PageRoot>
			<Title>SSL Certificates</Title>
			<Description>
				If this is your first time using my web services, and would like to get
				rid of the big red screen that screams security issues, you could
				download and install my root and intermediate SSL certificates:
			</Description>
			<LinksContainer>
				<Link download href="sidhartaCA.crt">Root</Link>
				<Link download href="web-services.crt">Intermediate</Link>
			</LinksContainer>

			<Subtitle warning>Before you install</Subtitle>
			<Description>
				Do not go around installing certificates from random pages on the web.
				There is a reason the big red security issue screen is so big. Only
				do this if you trust the authority that generated these certificates
				(in this case, me), and trust that authority's capacity to securely
				store that certificate's private key.
			</Description>
			<Description>
				I am by no means a security expert, and there is a reasonable chance
				that I'll fuck something up in the future. You've been warned.
			</Description>

			<Subtitle>How to install the certificates?</Subtitle>
			<Description>
				Installing the certificates is usually easy: just download both files and double-click them.
				When installing a certificate, you may be prompted where should it be installed.
				This is important because, if placed on the incorrect folder, your browser may
				not be able to use it properly. For the root certificate, select the
				"Trusted Root Certificates" option. For the intermediate certificate,
				select the "Trusted Intermediate Certificates" option.
			</Description>

			<Subtitle>Why do I have to install these certificates?</Subtitle>
			<Description>
				This is related to HTTPS and security. Your browser needs a signed certificate
				to make sure it's talking to the actual server, and not to some malicious server.
				Most websites's certificates are generated by trusted organizations, and
				your browser is already pre-programmed to trust the certificates generated
				by them. My certificates, however, were generated by me, and your browser
				doesn't trust me (rightly so!). By installing the two certificates above,
				you are basically telling your browser to trust the certificates generated
				by them (and therefore, the certificates generated by me).
			</Description>

			<Subtitle>Why aren't you using certificates from places like "Let's Encrypt"?</Subtitle>
			<Description>
				The main reason is because it seems like a bit of a nightmare to automate. I wanted
				a system to quickly and easily generate certificates for all my web projects,
				without having to visit a third party service, and verify the ownage of my
				domain name. The downside to this is that you have to install my certificates
				to stop your browser from complaining, but since this isn't really destined to
				be used by a broad audience, I think that's OK.
			</Description>
			<Description>
				Also, I really wanted to learn how a Certificate Authority works, how to create one,
				and how to automate the steps to generate a SSL certificate. It took me a few
				hours, and a lot of documentation reading, but I eventualy managed to do it,
				and am pretty proud of it :)
			</Description>
		</PageRoot>
	);
}

export default Certificates;